#!/usr/bin/env python3
"""Minimal offline DQN trainer for QoE-aware BS selection.

Input is a transition CSV generated by scripts/dqn/dataset/build_transitions.py.
The model learns Q(s, selected_bs_id) for Option A, where the target UE is
selected outside the DQN and the DQN selects only the destination BS.
"""

from __future__ import annotations

import argparse
import json
import random
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Sequence

import pandas as pd
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None


DEFAULT_FEATURE_COLUMNS = [
    "current_bs_id",
    "app_type",
    "tp_mbps",
    "rtt_ms",
    "satisfaction",
    "num_users_on_current_bs",
    "harmonic_mean",
    "num_unsatisfied_users",
]

DEFAULT_NEXT_FEATURE_COLUMNS = [
    "next_current_bs_id",
    "next_app_type",
    "next_tp_mbps",
    "next_rtt_ms",
    "next_satisfaction",
    "next_num_users_on_current_bs",
    "next_harmonic_mean",
    "next_num_unsatisfied_users",
]

REQUIRED_COLUMNS = set(DEFAULT_FEATURE_COLUMNS + DEFAULT_NEXT_FEATURE_COLUMNS + [
    "action_selected_bs_id",
    "reward",
    "done",
])


class QNetwork(nn.Module):
    def __init__(self, input_dim: int, output_dim: int, hidden_dims: Sequence[int]):
        super().__init__()
        layers: List[nn.Module] = []
        prev_dim = input_dim
        for hidden_dim in hidden_dims:
            layers.append(nn.Linear(prev_dim, hidden_dim))
            layers.append(nn.ReLU())
            prev_dim = hidden_dim
        layers.append(nn.Linear(prev_dim, output_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train a minimal offline DQN model.")
    parser.add_argument(
        "--input",
        "-i",
        nargs="+",
        required=True,
        help="Transition CSV file(s) or glob pattern(s).",
    )
    parser.add_argument(
        "--config",
        default="data/dqn/configs/dqn.yaml",
        help="DQN config YAML path.",
    )
    parser.add_argument(
        "--output",
        help="Checkpoint output path. If omitted, a timestamped file is created.",
    )
    parser.add_argument(
        "--result-dir",
        default="results/dqn",
        help="Directory to save training loss CSV/metadata.",
    )
    parser.add_argument("--epochs", type=int, help="Override number of offline training epochs.")
    parser.add_argument("--device", default="auto", choices=["auto", "cpu", "cuda"])
    return parser.parse_args()


def resolve_inputs(patterns: Sequence[str]) -> List[Path]:
    paths: List[Path] = []
    for pattern in patterns:
        p = Path(pattern)
        if p.exists():
            paths.append(p)
            continue
        paths.extend(sorted(Path().glob(pattern)))
    unique: List[Path] = []
    seen = set()
    for p in paths:
        r = p.resolve()
        if r not in seen:
            seen.add(r)
            unique.append(p)
    if not unique:
        raise FileNotFoundError(f"No input files matched: {patterns}")
    return unique


def load_config(path: Path) -> Dict:
    if not path.exists():
        return {}
    if yaml is None:
        raise RuntimeError("PyYAML is required to read YAML config files.")
    with path.open() as f:
        data = yaml.safe_load(f) or {}
    return data


def get_device(name: str) -> torch.device:
    if name == "cpu":
        return torch.device("cpu")
    if name == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("CUDA was requested but is not available.")
        return torch.device("cuda")
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def set_seed(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_transitions(paths: Sequence[Path]) -> pd.DataFrame:
    frames = [pd.read_csv(path) for path in paths]
    df = pd.concat(frames, ignore_index=True)
    missing = sorted(REQUIRED_COLUMNS - set(df.columns))
    if missing:
        raise ValueError(f"Transition CSV is missing required columns: {missing}")
    return df


def numeric_matrix(df: pd.DataFrame, columns: Sequence[str]) -> torch.Tensor:
    values = df.loc[:, columns].apply(pd.to_numeric, errors="raise").astype("float32")
    return torch.tensor(values.to_numpy(), dtype=torch.float32)


def normalize_pair(states: torch.Tensor, next_states: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    # Normalize with statistics from current states only to avoid leaking future distribution.
    mean = states.mean(dim=0)
    std = states.std(dim=0)
    std = torch.where(std < 1e-6, torch.ones_like(std), std)
    return (states - mean) / std, (next_states - mean) / std, mean, std


def make_output_path(config: Dict, output: str | None) -> Path:
    if output:
        return Path(output)
    scenario = config.get("scenario_name") or "static_80ue_5step"
    algorithm = config.get("algorithm", "dqn")
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return Path("models/dqn/checkpoints") / f"{algorithm}_{scenario}_{stamp}.pt"


def train() -> int:
    args = parse_args()
    config = load_config(Path(args.config))

    seed = int(config.get("seed", 1))
    set_seed(seed)
    device = get_device(args.device)

    gamma = float(config.get("gamma", 0.95))
    learning_rate = float(config.get("learning_rate", 1e-4))
    batch_size_cfg = int(config.get("batch_size", 32))
    target_update_interval = int(config.get("target_update_interval", 50))
    hidden_dims = list(config.get("hidden_dims", [128, 128]))
    epochs = int(args.epochs if args.epochs is not None else config.get("num_episodes", 50))
    action_dim = 3

    input_paths = resolve_inputs(args.input)
    df = load_transitions(input_paths)
    if df.empty:
        raise ValueError("Transition dataset is empty.")

    states = numeric_matrix(df, DEFAULT_FEATURE_COLUMNS)
    next_states = numeric_matrix(df, DEFAULT_NEXT_FEATURE_COLUMNS)
    states, next_states, state_mean, state_std = normalize_pair(states, next_states)

    actions = torch.tensor(pd.to_numeric(df["action_selected_bs_id"]).to_numpy(), dtype=torch.long)
    rewards = torch.tensor(pd.to_numeric(df["reward"]).to_numpy(), dtype=torch.float32)
    dones = torch.tensor(pd.to_numeric(df["done"]).to_numpy(), dtype=torch.float32)

    if actions.min().item() < 0 or actions.max().item() >= action_dim:
        raise ValueError(f"action_selected_bs_id must be in [0, {action_dim - 1}].")

    dataset = TensorDataset(states, actions, rewards, next_states, dones)
    batch_size = max(1, min(batch_size_cfg, len(dataset)))
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True, drop_last=False)

    q_net = QNetwork(states.shape[1], action_dim, hidden_dims).to(device)
    target_net = QNetwork(states.shape[1], action_dim, hidden_dims).to(device)
    target_net.load_state_dict(q_net.state_dict())
    target_net.eval()

    optimizer = torch.optim.Adam(q_net.parameters(), lr=learning_rate)
    loss_fn = nn.MSELoss()

    losses: List[Dict[str, float]] = []
    global_step = 0
    for epoch in range(1, epochs + 1):
        epoch_losses: List[float] = []
        for batch_states, batch_actions, batch_rewards, batch_next_states, batch_dones in loader:
            batch_states = batch_states.to(device)
            batch_actions = batch_actions.to(device)
            batch_rewards = batch_rewards.to(device)
            batch_next_states = batch_next_states.to(device)
            batch_dones = batch_dones.to(device)

            q_values = q_net(batch_states).gather(1, batch_actions.unsqueeze(1)).squeeze(1)
            with torch.no_grad():
                next_q_values = target_net(batch_next_states).max(dim=1).values
                targets = batch_rewards + gamma * (1.0 - batch_dones) * next_q_values

            loss = loss_fn(q_values, targets)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            global_step += 1
            if global_step % target_update_interval == 0:
                target_net.load_state_dict(q_net.state_dict())
            epoch_losses.append(float(loss.item()))

        mean_loss = sum(epoch_losses) / max(1, len(epoch_losses))
        losses.append({"epoch": epoch, "loss": mean_loss})
        if epoch == 1 or epoch % max(1, epochs // 10) == 0 or epoch == epochs:
            print(f"epoch={epoch}/{epochs} loss={mean_loss:.6f}")

    output_path = make_output_path(config, args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    checkpoint = {
        "model_state_dict": q_net.state_dict(),
        "target_model_state_dict": target_net.state_dict(),
        "feature_columns": DEFAULT_FEATURE_COLUMNS,
        "next_feature_columns": DEFAULT_NEXT_FEATURE_COLUMNS,
        "state_mean": state_mean.tolist(),
        "state_std": state_std.tolist(),
        "action_dim": action_dim,
        "hidden_dims": hidden_dims,
        "gamma": gamma,
        "seed": seed,
        "input_files": [str(p) for p in input_paths],
        "num_transitions": len(df),
        "config": config,
    }
    torch.save(checkpoint, output_path)

    result_dir = Path(args.result_dir)
    result_dir.mkdir(parents=True, exist_ok=True)
    stem = output_path.stem
    loss_path = result_dir / f"train_loss_{stem}.csv"
    pd.DataFrame(losses).to_csv(loss_path, index=False)
    meta_path = result_dir / f"train_meta_{stem}.json"
    meta = {
        "checkpoint": str(output_path),
        "loss_csv": str(loss_path),
        "num_transitions": len(df),
        "batch_size": batch_size,
        "epochs": epochs,
        "device": str(device),
        "input_files": [str(p) for p in input_paths],
    }
    meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")

    print(f"saved checkpoint: {output_path}")
    print(f"saved loss csv: {loss_path}")
    print(f"saved metadata: {meta_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(train())
